### ISSUE TITLE
error message during training

### ISSUE THREAD

**Issue by jalimena** [DL4Jets/DeepJetCore#47]
```
23704/23744 [============================>.] - ETA: 3s - loss: 0.1886 - accuracy: 0.93302020-06-11 15:59:49.987054: W tensorflow/core/framework/op_kernel.cc:1643] Unknown: Exception: DataCollection.generatorFunction: generator ran out of samples. This should not have happened, please report bug.
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/script_ops.py", line 236, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 789, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 889, in wrapped_generator
    for batch in generator_fn():

  File "/usr/share/DJC/DeepJetCore/DataCollection.py", line 595, in generatorFunction
    raise Exception("DataCollection.generatorFunction: generator ran out of samples. This should not have happened, please report bug.")

Exception: DataCollection.generatorFunction: generator ran out of samples. This should not have happened, please report bug.


23743/23744 [============================>.] - ETA: 0s - loss: 0.1886 - accuracy: 0.9330

2020-06-11 16:07:01.548097: W tensorflow/core/framework/op_kernel.cc:1643] Unknown: Exception: DataCollection.generatorFunction: generator ran out of samples. This should not have happened, please report bug.
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/script_ops.py", line 236, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 789, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 889, in wrapped_generator
    for batch in generator_fn():

  File "/usr/share/DJC/DeepJetCore/DataCollection.py", line 595, in generatorFunction
    raise Exception("DataCollection.generatorFunction: generator ran out of samples. This should not have happened, please report bug.")

Exception: DataCollection.generatorFunction: generator ran out of samples. This should not have happened, please report bug.



***callbacks***
saving losses to /afs/cern.ch/work/j/jalimena/DisplacedHGCalL1/HGCalL1Images/Train/TrainOutput/losses.log
/usr/share/DJC/DeepJetCore/evaluation/evaluation.py:339: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

Epoch 00001: val_loss improved from inf to 0.18676, saving model to /afs/cern.ch/work/j/jalimena/DisplacedHGCalL1/HGCalL1Images/Train/TrainOutput//KERAS_check_best_model.h5

Epoch 00001: saving model to /afs/cern.ch/work/j/jalimena/DisplacedHGCalL1/HGCalL1Images/Train/TrainOutput//KERAS_check_model_block_0_epoch_01.h5

***callbacks end***
```

As you can see, an exception was thrown, but then the training continued.

**Comment by jkiesele** [comment]
Thanks, on it

**Comment by jkiesele** [comment]
This should be fixed now.
b20cdcbe54c41685f61dba0b40e05026c83c981f
